# state dimension, control dimension
/variable_num/state: 4
/variable_num/control: 2

# timestep of prediction, planning and control
/timestep/planning: 0.1
/timestep/control: 0.05
/timestep/prediction: 0.05
/timestep/multiple/planner_start_index: 18

# params for building scene
/planner/global_file_path: "/home/saxijing/cilqr/data/static_avoid_centerline.csv"
/road_info/lane_width: 3.5
/road_info/lane_num: 2
/obstacle/max_perception_dist: 200
/scenario/ego/initial_speed: 5.0

# horizon
/planner/global_horizon: 20
/planner/local_horizon: 70
/planner/prediction_horizon: 70

# iLQR solver params
/planner/poly_order: 5
/planner/safe_dist/a: 10.0
/planner/safe_dist/b: 4.0
/planner/safe_time: 0.1
/planner/ego_radius: 2.0
/planner/ego_lf: 2.875
/planner/ego_lr: 0.0
/planner/forward/line_search/beta_min: 1.0e-4
/planner/forward/line_search/beta_max: 10
/planner/forward/line_search/gama: 0.5
/planner/forward/linear_search/max_iterate: 20
/planner/optimal/max_iterate: 100
/planner/optimal/lamb/init: 1.0
/planner/optimal/lamb/decay: 0.7
/planner/optimal/lamb/amplify: 2.0
/planner/optimal/lamb/max: 1000
/planner/optimal/tol: 0.001
/planner/error/start_dist: 30.0

# weights
/planner/weight/iLQR/w_pos: 5.0
/planner/weight/iLQR/w_vel: 0.1
/planner/weight/iLQR/w_theta: 0.5
/planner/weight/iLQR/w_accel: 0.1
/planner/weight/iLQR/w_yawrate: 10.0
/planner/weight/obstacle/q1_front: 2.75
/planner/weight/obstacle/q2_front: 2.75
/planner/weight/obstacle/q1_rear: 2.75
/planner/weight/obstacle/q2_rear: 2.75
/planner/weight/control/q1_acc: 1.0
/planner/weight/control/q2_acc: 1.0
/planner/weight/control/q1_yawrate: 1.0
/planner/weight/control/q2_yawrate: 1.0

# constraints
/planner/constraints/control/min_accel: -5.5 #m/s2
/planner/constraints/control/max_accel: 2.0 #m/s2
/planner/constraints/control/min_wheel_angle: -1.0 #radius
/planner/constraints/control/max_wheel_angle: 1.0 #radius

# hardware params
/ego_vehicle/wheel_base: 2.875
/ego_vehicle/height: 1.44
/ego_vehicle/width: 1.85
/ego_vehicle/max_speed: 30.0




